name: Build and Test

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.17

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r src/user_service/requirements.txt
          pip install pytest

      - name: Validate SAM template        
        run: |
          sam validate --region eu-west-1

      - name: Run tests
        run: |
          pytest tests

      - name: Sam build
        run: |
          sam build --use-container  --region eu-west-1
