name: Deploy to AWS

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1
  DEFAULT_STACK_NAME: lambda-user-service
  DEFAULT_TABLE_NAME: UserTable

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: AWS
      url: https://console.aws.amazon.com/cloudformation

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/Github_Actions_Role
          aws-region: ${{ env.AWS_REGION }}


      - name: Set environment variables
        run: |
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "STACK_NAME=${{ env.DEFAULT_STACK_NAME }}" >> $GITHUB_ENV
            echo "USER_TABLE=${{ env.DEFAULT_TABLE_NAME }}" >> $GITHUB_ENV
          else
            SAFE_BRANCH=$(echo "$BRANCH_NAME" | tr '/' '-') # Can't use / in resource names
            echo "STACK_NAME=${{ env.DEFAULT_STACK_NAME }}-$SAFE_BRANCH" >> $GITHUB_ENV
            echo "USER_TABLE=${{ env.DEFAULT_TABLE_NAME }}-$SAFE_BRANCH" >> $GITHUB_ENV
          fi

      - name: Build with SAM
        run: |
          sam build --use-container --region $AWS_REGION

      - name: Deploy with SAM
        run: |
          sam deploy --stack-name $STACK_NAME \
                     --parameter-overrides USER_TABLE=$USER_TABLE \
                     --region $AWS_REGION \
                     --capabilities CAPABILITY_IAM \
                     --resolve-s3 \
                     --no-confirm-changeset \
                     --no-fail-on-empty-changeset
