name: Teardown AWS Stack

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1
  DEFAULT_STACK_NAME: lambda-user-service

jobs:
  delete-stack:
    runs-on: ubuntu-latest
    environment: AWS

    permissions:
      id-token: write
      contents: read

    env:
      BRANCH_NAME: ${{ github.ref_name }}
      SANITIZED_BRANCH: ${{ github.ref_name == 'main' && '' || github.ref_name.replace('/', '-') }}
      STACK_NAME: ${{ github.ref_name == 'main' && env.DEFAULT_STACK_NAME || format('{0}-{1}', env.DEFAULT_STACK_NAME, env.SANITIZED_BRANCH) }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::694880089996:role/Github_Actions_Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete stack
        run: sam delete --stack-name $STACK_NAME --no-prompts
