name: Teardown AWS Stack

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1
  DEFAULT_STACK_NAME: lambda-user-service

jobs:
  delete-stack:
    runs-on: ubuntu-latest
    environment: AWS

    permissions:
      id-token: write
      contents: read

    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::694880089996:role/Github_Actions_Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set environment variables
        run: |
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "STACK_NAME=${{ env.DEFAULT_STACK_NAME }}" >> $GITHUB_ENV
          else
            SAFE_BRANCH=$(echo "$BRANCH_NAME" | tr '/' '-') # Can't use / in resource names
            echo "STACK_NAME=${{ env.DEFAULT_STACK_NAME }}-$SAFE_BRANCH" >> $GITHUB_ENV
          fi

      - name: Delete stack
        run: sam delete --stack-name $STACK_NAME --no-prompts
